This project combines machine learning and operations research to forecast product demand using XGBoost and optimize inventory allocation using linear programming.

Objectives

- Forecast product demand over a 28-day horizon.
- Identify key drivers of retail demand.
- Optimize inventory allocation across stores.
- Evaluate inventory strategies under different business scenarios.

Optimization
- Total Inventory Cost
- Service Level
- Stockout Rate
- Inventory Utilization

In [ ]:
# Import core libraries for data analysis
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Configure notebook display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [ ]:
from src.utils.project_setup import *

from src.data.loader import load_data

calendar, sales, prices = load_data()

print(f"Calendar: {calendar.shape}")
print(f"Sales: {sales.shape}")
print(f"Prices: {prices.shape}")

Calendar: (1969, 14)
Sales: (30490, 1919)
Prices: (6841121, 4)

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [9]:
# Review the calendar table structure
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 1969 entries, 0 to 1968
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          1969 non-null   str
 1   wm_yr_wk      1969 non-null   int64
 2   weekday       1969 non-null   str
 3   wday          1969 non-null   int64
 4   month         1969 non-null   int64
 5   year          1969 non-null   int64
 6   d             1969 non-null   str
 7   event_name_1  162 non-null    str
 8   event_type_1  162 non-null    str
 9   event_name_2  5 non-null      str
 10  event_type_2  5 non-null      str
 11  snap_CA       1969 non-null   int64
 12  snap_TX       1969 non-null   int64
 13  snap_WI       1969 non-null   int64
dtypes: int64(7), str(7)
memory usage: 215.5 KB

In [10]:
calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI
0,2011-01-29,11101,Saturday,1,1,2011,d_1,NaN,NaN,NaN,NaN,0,0,0
1,2011-01-30,11101,Sunday,2,1,2011,d_2,NaN,NaN,NaN,NaN,0,0,0
2,2011-01-31,11101,Monday,3,1,2011,d_3,NaN,NaN,NaN,NaN,0,0,0
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,NaN,NaN,NaN,NaN,1,1,0
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,NaN,NaN,NaN,NaN,1,0,1

In [11]:
# Review the sales table structure
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 30490 entries, 0 to 30489
Columns: 1919 entries, id to d_1913
dtypes: int64(1913), str(6)
memory usage: 446.4 MB

In [12]:
sales.iloc[:, :10].head()

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0

In [13]:
# Review the prices table structure
prices.info()

<class 'pandas.DataFrame'>
RangeIndex: 6841121 entries, 0 to 6841120
Data columns (total 4 columns):
 #   Column      Dtype
---  ------      -----
 0   store_id    str
 1   item_id     str
 2   wm_yr_wk    int64
 3   sell_price  float64
dtypes: float64(1), int64(1), str(2)
memory usage: 208.8 MB

In [14]:
prices.head()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [15]:
dataset_inventory = pd.DataFrame({
    "Dataset": ["Calendar", "Sales", "Prices"],
    "Rows": [
        calendar.shape[0],
        sales.shape[0],
        prices.shape[0]
    ],
    "Columns": [
        calendar.shape[1],
        sales.shape[1],
        prices.shape[1]
    ]
})

dataset_inventory

    Dataset     Rows  Columns
0  Calendar     1969       14
1     Sales    30490     1919
2    Prices  6841121        4